[env:esp32-c6-devkitc-1]
; Use the community-supported platform for Arduino 3.0+
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.20/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino
board_build.filesystem = littlefs

lib_deps = 
    bblanchon/ArduinoJson@^7.2.2
    esp32async/ESPAsyncWebServer@^3.10.3
    esp32async/AsyncTCP@^3.4.10
    adafruit/Adafruit BMP280 Library @ ^2.6.8
    


board_build.partitions = huge_app.csv

upload_port = COM15
monitor_port = COM15

build_flags =
    -D CONFIG_LWIP_IPV6=0
    -std=gnu++17
    -isystem "${platformio.packages_dir}/toolchain-riscv32-esp/lib/gcc/riscv32-esp-elf/14.2.0/include"
    -isystem "${platformio.packages_dir}/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/14.2.0"
    -isystem "${platformio.packages_dir}/toolchain-riscv32-esp/riscv32-esp-elf/include/c++/14.2.0/riscv32-esp-elf"

build_unflags =
    -std=gnu++11